notifications:
  email:
    on_success: never
    on_failure: always
sudo: required
services:
    - docker
language: bash
branches:
  only:
    - develop
env:
  global:
    - NAME=sensiot
    - VERSION=develop

jobs:
  include:
    - stage: Build images
      before_install:
        - docker pull "${DOCKER_USER}/${NAME}:${VERSION}-${ARCH}" || true
      env:
        - ARCH=amd64
      script: make
    -
      before_install:
        - docker pull "${DOCKER_USER}/${NAME}:${VERSION}-${ARCH}" || true
      env:
        - ARCH=arm
      script: make
    - stage: Make manifest
      script: make manifest