{
 "title": "SENSIOT",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "10s,30s,1m,2m,5m,10m,30m,1h,6h,12h"
   },
   { "name": "sensor", "query": "temperature,humidity" },
   { "name": "sensor_id", "query": "1,2,3,4,5" }
  ]
 },
 "panels": [
  {
   "title": "SensIoT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"sensiot:.*\", name=\"$sensor\"}[$interval])",
     "legendFormat": "{{building}}.{{room}}.{{sensor_id}}"
    },
    {}
   ]
  },
  {
   "title": "Temperature of Sensor $sensor_id ",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "format": "celsius",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"sensiot:.*:$sensor_id\", name=\"temperature\"}[$interval])"
    }
   ]
  },
  {
   "title": "Humidity of Sensor $sensor_id",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "format": "humidity",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"sensiot:.*:$sensor_id\", name=\"humidity\"}[$interval])"
    }
   ]
  }
 ]
}