global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'sensiot'
scrape_configs:
  - job_name: 'sensors'
    scrape_interval: 1s
    static_configs:
         - targets: ['prometheus_writer:8000']
  - job_name: 'cadvisor'
    scrape_interval: 1s
    static_configs:
         - targets: ['cadvisor:8080']